/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.ConexionDB;


/**
 *
 * @author EstudianteUnivalle
 */
public class ActualizarEmpleado extends javax.swing.JDialog {

    /**
     * Creates new form ActualizarCli
     */
    public ActualizarEmpleado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("../img/iconoUnivalle.JPG")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        NombreEmp = new javax.swing.JTextField();
        DireccionEmp = new javax.swing.JTextField();
        ApellidoEmp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        SalarioEmp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TelefonoEmp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CargoEmp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        NominaEmp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        BusesEmp = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(420, 630));
        setModal(true);
        getContentPane().setLayout(null);

        botonGuardar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botonGuardar.setText("GUARDAR");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(botonGuardar);
        botonGuardar.setBounds(125, 492, 125, 33);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(71, 84, 47, 24);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("NOMBRE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(71, 127, 80, 24);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("DIRECCION");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(68, 428, 101, 24);

        jLabel4.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jLabel4.setText("ACTUALIZAR EMPLEADO");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(22, 21, 373, 33);
        getContentPane().add(ID);
        ID.setBounds(184, 89, 84, 30);

        NombreEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreEmpActionPerformed(evt);
            }
        });
        getContentPane().add(NombreEmp);
        NombreEmp.setBounds(184, 132, 84, 30);

        DireccionEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DireccionEmpActionPerformed(evt);
            }
        });
        getContentPane().add(DireccionEmp);
        DireccionEmp.setBounds(187, 433, 83, 30);
        getContentPane().add(ApellidoEmp);
        ApellidoEmp.setBounds(184, 175, 84, 30);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("APELLIDO");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(71, 170, 91, 24);
        getContentPane().add(SalarioEmp);
        SalarioEmp.setBounds(184, 347, 84, 30);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("SALARIO");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(71, 342, 81, 24);
        getContentPane().add(TelefonoEmp);
        TelefonoEmp.setBounds(184, 390, 84, 30);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("TELEFONO");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(71, 385, 98, 24);

        CargoEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargoEmpActionPerformed(evt);
            }
        });
        getContentPane().add(CargoEmp);
        CargoEmp.setBounds(184, 304, 84, 30);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("Cargo");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(71, 299, 52, 24);

        NominaEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NominaEmpActionPerformed(evt);
            }
        });
        getContentPane().add(NominaEmp);
        NominaEmp.setBounds(184, 218, 84, 30);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setText("Nomina");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(71, 213, 67, 24);
        getContentPane().add(BusesEmp);
        BusesEmp.setBounds(184, 261, 84, 30);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setText("Buses");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(71, 256, 55, 24);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 551, 79, 33);

        jButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton2.setText("Inicio");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(125, 551, 79, 33);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/facturacion.jpg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 430, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
  if(
            ID.getText().equals("")||
            NominaEmp.getText().equals("")||
          BusesEmp.getText().equals("")||
          ApellidoEmp.getText().equals("")||
          CargoEmp.getText().equals("")||
          SalarioEmp.getText().equals("")||
          TelefonoEmp.getText().equals("")||
          DireccionEmp.getText().equals("")
           )
        {
          JOptionPane.showMessageDialog(this,"Llenar los valores a continuación"); 
          
        }else{
        try{
        ConexionDB conexion = new ConexionDB();
        String id = ID.getText();
        String Nomina = NominaEmp.getText();
        String Buses = BusesEmp.getText();
        String nombre = NombreEmp.getText();
        String Apellido = ApellidoEmp.getText();
        String Cargo = CargoEmp.getText();
        String Salario = SalarioEmp.getText();
        String Telefono = TelefonoEmp.getText();
        String Direccion = DireccionEmp.getText();

        String sql = "UPDATE Empleados SET Nombre = '";
        sql +=  nombre + "', idNomina = '" + Nomina +"', Buses_idBuses = '" + Buses +"', Apellido = '" + Apellido +"', idCargo = '" + Cargo +"', Salario = '" + Salario +"', Telefono = '" + Telefono +"', Direccion = '" + Direccion + "' WHERE idEmpleados = '" + id + "'";
        conexion.Sentencia(sql);
        setVisible(false);
        JOptionPane.showMessageDialog(this,"Datos Ingresados Exitosamente");
   } catch(Exception e){
                JOptionPane.showMessageDialog(this,"Llenar los valores a continuación");
                System.out.println(e.getMessage());
              }
  }
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void NombreEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreEmpActionPerformed

    private void DireccionEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DireccionEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DireccionEmpActionPerformed

    private void CargoEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargoEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CargoEmpActionPerformed

    private void NominaEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NominaEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NominaEmpActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        new VentanaPrincipalEmpleados().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new VentanaPrincipal().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ActualizarEmpleado dialog = new ActualizarEmpleado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoEmp;
    private javax.swing.JTextField BusesEmp;
    private javax.swing.JTextField CargoEmp;
    private javax.swing.JTextField DireccionEmp;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField NombreEmp;
    private javax.swing.JTextField NominaEmp;
    private javax.swing.JTextField SalarioEmp;
    private javax.swing.JTextField TelefonoEmp;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
