/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.ConexionDB;




/**
 *
 * @author EstudianteUnivalle
 */
public class Facturacion extends javax.swing.JDialog {

    ConexionDB conexion;

    public Facturacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("../img/iconoUnivalle.JPG")).getImage());
        conexion = new ConexionDB();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        InCedula = new javax.swing.JTextField();
        InNombre = new javax.swing.JTextField();
        InApellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Destinos = new javax.swing.JComboBox<>();
        botonAceptar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        outTotal = new javax.swing.JTextField();
        InPrecio = new javax.swing.JTextField();
        InCantidad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        InDia = new javax.swing.JSpinner();
        Meses = new javax.swing.JComboBox<>();
        InAño = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        InBus = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        InIDFactura = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(592, 500));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        jLabel1.setText("FACTURACION");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(162, 11, 163, 25);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("NOMBRE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 152, 80, 24);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("APELLIDO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 195, 91, 24);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("CEDULA");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 105, 75, 24);
        getContentPane().add(InCedula);
        InCedula.setBounds(226, 110, 70, 30);
        getContentPane().add(InNombre);
        InNombre.setBounds(226, 157, 70, 30);
        getContentPane().add(InApellido);
        InApellido.setBounds(226, 200, 70, 30);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("DESTINO");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(382, 105, 80, 24);

        Destinos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cali", "Palmira", "Buga", "Zarzal", "Cartago", "Yumbo", "Buenaventura", "Tulua" }));
        Destinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DestinosActionPerformed(evt);
            }
        });
        getContentPane().add(Destinos);
        Destinos.setBounds(480, 110, 93, 20);

        botonAceptar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(botonAceptar);
        botonAceptar.setBounds(391, 350, 101, 33);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("PRECIO");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(382, 152, 69, 24);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("CANTIDAD ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(382, 195, 99, 24);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("TOTAL ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(162, 354, 65, 24);

        outTotal.setEditable(false);
        getContentPane().add(outTotal);
        outTotal.setBounds(245, 359, 95, 30);
        getContentPane().add(InPrecio);
        InPrecio.setBounds(499, 157, 69, 30);
        getContentPane().add(InCantidad);
        InCantidad.setBounds(499, 200, 69, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Fecha De Venta");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 246, 107, 17);
        getContentPane().add(InDia);
        InDia.setBounds(10, 290, 51, 30);

        Meses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        getContentPane().add(Meses);
        Meses.setBounds(71, 290, 79, 20);
        getContentPane().add(InAño);
        InAño.setBounds(168, 290, 74, 30);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel10.setText("Dia");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(24, 268, 18, 16);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel11.setText("Mes");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(93, 268, 24, 16);

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel12.setText("Año");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(192, 268, 22, 16);

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setText("BUS");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(333, 231, 38, 24);
        getContentPane().add(InBus);
        InBus.setBounds(499, 236, 69, 30);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setText("NUMERO FACTURA");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(10, 62, 172, 24);
        getContentPane().add(InIDFactura);
        InIDFactura.setBounds(226, 67, 70, 30);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("Inicio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 410, 79, 33);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/facturacion.jpg"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(0, 0, 590, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DestinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DestinosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DestinosActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed

       //  if (JOptionPane.showConfirmDialog(this, " LLenar los valores antes de continuar ")== 0){
             
              try{
                  
                   String Id_Cliente = InCedula.getText();
        String ID_Factura = InIDFactura.getText();
        String name = InNombre.getText();
        String apellido = InApellido.getText();
        String precio = InPrecio.getText();
        String cantidad = InCantidad.getText();
        String bus = InBus.getText();
        // String dia = InDia.toString();
        String mes = (String) Meses.getSelectedItem();
        // String año = InAño.toString();
        String destino = (String) Destinos.getSelectedItem();

        /*SpinnerNumberModel model = new SpinnerNumberModel(
                new Integer(1), // Dato visualizado al inicio en el spinner 
                new Integer(1), // Límite inferior 
                new Integer(31), // Límite superior 
                new Integer(1) // incremento-decremento 
        );*/

       // JSpinner InDia = new JSpinner(model);
        
        String dia = InDia.getValue().toString();
;
        String año = InAño.getValue().toString();;
        int precio1 = Integer.parseInt(InPrecio.getText());
        int cantidad1 = Integer.parseInt(InCantidad.getText());
        
       

        String fecha = dia + "/" + mes + "/" + año;
        int resultado = precio1 * cantidad1;
        String total = "" + resultado;

        String sql = "INSERT INTO Factura (idFactura, idBuses, idCliente, Precio, FechaHora, Destino)";
        sql += " VALUES ( '" + ID_Factura + "', '" + bus + "', '" + Id_Cliente + "', '" + total + "', '" + fecha + "', '" + destino + "')";
        conexion.Sentencia(sql);
        setVisible(true);
        
       /* String sql1 = "INSERT INTO Cliente (idCliente, Nombre, Apellido)";
        sql1 += " VALUES ( '" + Id_Cliente + "', '" + name + "', '" + apellido + "')";
        conexion.Sentencia(sql1);*/

        outTotal.setText(total);
         
          
      }
              catch(Exception e){
                JOptionPane.showMessageDialog(this,"Llenar los valores a continuación");
                System.out.println(e.getMessage());
              }
             
             
       
     
            
       
           
        
      //   }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new VentanaPrincipal().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Facturacion dialog = new Facturacion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Destinos;
    private javax.swing.JTextField InApellido;
    private javax.swing.JSpinner InAño;
    private javax.swing.JTextField InBus;
    private javax.swing.JTextField InCantidad;
    private javax.swing.JTextField InCedula;
    private javax.swing.JSpinner InDia;
    private javax.swing.JTextField InIDFactura;
    private javax.swing.JTextField InNombre;
    private javax.swing.JTextField InPrecio;
    private javax.swing.JComboBox<String> Meses;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField outTotal;
    // End of variables declaration//GEN-END:variables
}
