
package VistaNomina;

import VistaCargos.*;
import VistaBuses.*;
import javax.swing.ImageIcon;

import javax.swing.JOptionPane;
import modelo.ConexionDB;
import vistas.VentanaPrincipal;


/**
 *
 * @author EstudianteUnivalle
 */
public class ActualizarNomina extends javax.swing.JDialog {

    /**
     * Creates new form ActualizarCli
     */
    public ActualizarNomina(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("../img/iconoUnivalle.JPG")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        botonGuardar = new javax.swing.JButton();
        IDNomina = new javax.swing.JTextField();
        IDGastos = new javax.swing.JTextField();
        Volver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        PLACA1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 360));
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        jLabel4.setText("ACTUALIZAR");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(137, 26, 150, 25);

        botonGuardar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botonGuardar.setText("GUARDAR");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(botonGuardar);
        botonGuardar.setBounds(148, 201, 125, 33);
        getContentPane().add(IDNomina);
        IDNomina.setBounds(235, 95, 83, 30);

        IDGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDGastosActionPerformed(evt);
            }
        });
        getContentPane().add(IDGastos);
        IDGastos.setBounds(235, 143, 83, 30);

        Volver.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Volver.setText("Atras");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Volver);
        Volver.setBounds(10, 257, 79, 33);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("IDNomina :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 96, 97, 24);

        PLACA1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        PLACA1.setText("         IDGastos");
        getContentPane().add(PLACA1);
        PLACA1.setBounds(74, 138, 124, 24);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("Inicio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(107, 257, 79, 33);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/emple.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 450, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
  if(
            IDNomina.getText().equals("")||
            IDGastos.getText().equals("")
          
           )
        {
          JOptionPane.showMessageDialog(this,"Llenar los valores a continuación"); 
          
        }else{
        try{
        ConexionDB conexion = new ConexionDB();
        String id = IDNomina.getText();
        String Gastos = IDGastos.getText();
        

        String sql = "UPDATE Nomina SET Gastos_idGastos = '";
        sql +=  Gastos +"'WHERE idNomina = '" + id + "'";
        conexion.Sentencia(sql);
        setVisible(true);
        JOptionPane.showMessageDialog(this,"Datos Actualizados Exitosamente");
   } catch(Exception e){
                JOptionPane.showMessageDialog(this,"Llenar los valores a continuación");
                System.out.println(e.getMessage());
              }
  }
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void IDGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDGastosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDGastosActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed

        this.setVisible(false);
        new VentanaPrincipalNomina().setVisible(true);
    }//GEN-LAST:event_VolverActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new VentanaPrincipal().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ActualizarNomina dialog = new ActualizarNomina(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDGastos;
    private javax.swing.JTextField IDNomina;
    private javax.swing.JLabel PLACA1;
    private javax.swing.JButton Volver;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
