
package VistaNomina;

import VistaCargos.*;
import VistaBuses.*;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.ConexionDB;
import vistas.VentanaPrincipal;
/**
 *
 * @author EstudianteUnivalle
 */
public class VentanaPrincipalNomina extends javax.swing.JFrame {

    DefaultTableModel modelo;
    ConexionDB conexion;
    public VentanaPrincipalNomina() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("../img/iconoUnivalle.JPG")).getImage());
        modelo = (DefaultTableModel)TablaDatos.getModel();
        conexion = new ConexionDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonConsultar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaDatos = new javax.swing.JTable();
        AdicionarNomina = new javax.swing.JButton();
        BotonActualizar = new javax.swing.JButton();
        TotalNomina = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(null);

        botonConsultar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botonConsultar.setText("Consultar");
        botonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(botonConsultar);
        botonConsultar.setBounds(170, 107, 117, 33);

        TablaDatos.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        TablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idNomina", "IDGastos"
            }
        ));
        jScrollPane2.setViewportView(TablaDatos);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(83, 158, 127, 121);

        AdicionarNomina.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        AdicionarNomina.setText("Adicionar");
        AdicionarNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarNominaActionPerformed(evt);
            }
        });
        getContentPane().add(AdicionarNomina);
        AdicionarNomina.setBounds(26, 107, 115, 33);

        BotonActualizar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BotonActualizar.setText("Actualizar");
        BotonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonActualizar);
        BotonActualizar.setBounds(305, 107, 119, 33);

        TotalNomina.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        TotalNomina.setText("Total Nomina");
        TotalNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalNominaActionPerformed(evt);
            }
        });
        getContentPane().add(TotalNomina);
        TotalNomina.setBounds(270, 250, 147, 29);

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        jLabel1.setText("VENTANA PRINCIPAL NOMINA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(69, 22, 340, 25);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("Inicio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 306, 79, 33);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/factura1.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 500, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarActionPerformed

        ArrayList<String[]> datos = conexion.consulta("SELECT idNomina,Gastos_idGastos FROM Nomina order by idNomina");
        //Salida.setText(datos);
        DefaultTableModel modelo = (DefaultTableModel)TablaDatos.getModel();
        //String cadena ="";
        while(modelo.getRowCount() > 0)
        modelo.removeRow(modelo.getRowCount()-1);

        for (int i = 0; i<datos.size(); i++){
            String[] fila = datos.get(i);
            modelo.addRow(fila);
       
        }
    }//GEN-LAST:event_botonConsultarActionPerformed

    private void AdicionarNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarNominaActionPerformed

          this.setVisible(false);
        new NuevaNomina(this,true).setVisible(true);

    }//GEN-LAST:event_AdicionarNominaActionPerformed

    private void BotonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActualizarActionPerformed
      
        
          this.setVisible(false);
        new ActualizarNomina(this,true).setVisible(true);
    }//GEN-LAST:event_BotonActualizarActionPerformed

    private void TotalNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalNominaActionPerformed
       this.setVisible(false);
        new TotalNomina().setVisible(true);
    }//GEN-LAST:event_TotalNominaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new VentanaPrincipal().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipalNomina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdicionarNomina;
    private javax.swing.JButton BotonActualizar;
    private javax.swing.JTable TablaDatos;
    private javax.swing.JButton TotalNomina;
    private javax.swing.JButton botonConsultar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
