
package VistaCargos;

import VistaBuses.*;
import javax.swing.ImageIcon;


import javax.swing.JOptionPane;
import modelo.ConexionDB;
import vistas.VentanaPrincipal;

/**
 *
 * @author EstudianteUnivalle
 */
public class NuevaCargo extends javax.swing.JDialog {

    /**
     * Creates new form NuevoCliente
     */
    public NuevaCargo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("../img/iconoUnivalle.JPG")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PLACA = new javax.swing.JLabel();
        InPlacaBus = new javax.swing.JTextField();
        InCapacidadBus = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        InIDBus = new javax.swing.JTextField();
        BotonGuardar = new javax.swing.JButton();
        InIDCargo = new javax.swing.JTextField();
        InNombreCargo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PLACA1 = new javax.swing.JLabel();
        Volver = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        PLACA.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        PLACA.setText("PLACA");

        InPlacaBus.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        InPlacaBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InPlacaBusActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel13.setText("Ingresar Los Datos Del Cliente");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setText("IDBUS :");

        jLabel11.setText("Capacidad");

        InIDBus.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        InIDBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InIDBusActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 320));
        setMinimumSize(new java.awt.Dimension(500, 320));
        getContentPane().setLayout(null);

        BotonGuardar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BotonGuardar.setText("Guardar");
        BotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonGuardar);
        BotonGuardar.setBounds(141, 188, 103, 33);

        InIDCargo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        InIDCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InIDCargoActionPerformed(evt);
            }
        });
        getContentPane().add(InIDCargo);
        InIDCargo.setBounds(182, 92, 108, 30);

        InNombreCargo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        InNombreCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InNombreCargoActionPerformed(evt);
            }
        });
        getContentPane().add(InNombreCargo);
        InNombreCargo.setBounds(180, 140, 108, 30);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("IDCargo :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 95, 82, 24);

        jLabel4.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        jLabel4.setText("Ingresar Los Datos Del Cargo");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(81, 22, 288, 25);

        PLACA1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        PLACA1.setText("NombreCargo:");
        getContentPane().add(PLACA1);
        PLACA1.setBounds(41, 143, 129, 24);

        Volver.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Volver.setText("Atras");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Volver);
        Volver.setBounds(10, 238, 79, 33);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("Inicio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(117, 238, 79, 33);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/emple.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 560, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InIDBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InIDBusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InIDBusActionPerformed

    private void InPlacaBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InPlacaBusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InPlacaBusActionPerformed

    private void BotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarActionPerformed
  if(
            InIDCargo.getText().equals("")||
            InNombreCargo.getText().equals("")
            
           )
        {
          JOptionPane.showMessageDialog(this,"Llenar los valores a continuación"); 
          
        }else{
        try{
        ConexionDB conexion = new ConexionDB();
        String id = InIDCargo.getText();
        String cargo = InNombreCargo.getText();
        
        

        String sql = "INSERT INTO Cargo (idCargo,Nombre_Cargo)";
        sql += "VALUES ('"+id+"','"+cargo+"')";
        conexion.Sentencia(sql);
        setVisible(true);
        JOptionPane.showMessageDialog(this,"Datos Ingresados Exitosamente");
   } catch(Exception e){
                JOptionPane.showMessageDialog(this,"Llenar los valores a continuación");
                System.out.println(e.getMessage());
              } 
    }
    }//GEN-LAST:event_BotonGuardarActionPerformed

    private void InIDCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InIDCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InIDCargoActionPerformed

    private void InNombreCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InNombreCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InNombreCargoActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed

        this.setVisible(false);
        new VentanaPrincipalCargo().setVisible(true);
    }//GEN-LAST:event_VolverActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        this.setVisible(false);
        new VentanaPrincipal().setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NuevaCargo dialog = new NuevaCargo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonGuardar;
    private javax.swing.JTextField InCapacidadBus;
    private javax.swing.JTextField InIDBus;
    private javax.swing.JTextField InIDCargo;
    private javax.swing.JTextField InNombreCargo;
    private javax.swing.JTextField InPlacaBus;
    private javax.swing.JLabel PLACA;
    private javax.swing.JLabel PLACA1;
    private javax.swing.JButton Volver;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
