
package VistaCargos;

import VistaBuses.*;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.ConexionDB;
import vistas.VentanaPrincipal;

/**
 *
 * @author EstudianteUnivalle
 */
public class VentanaPrincipalCargo extends javax.swing.JFrame {

    DefaultTableModel modelo;
    ConexionDB conexion;
    public VentanaPrincipalCargo() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("../img/iconoUnivalle.JPG")).getImage());
        modelo = (DefaultTableModel)TablaDatos.getModel();
        conexion = new ConexionDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonConsultar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaDatos = new javax.swing.JTable();
        AdicionarCargo = new javax.swing.JButton();
        BotonActualizar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(650, 400));
        getContentPane().setLayout(null);

        botonConsultar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botonConsultar.setText("Consultar");
        botonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(botonConsultar);
        botonConsultar.setBounds(350, 70, 117, 33);

        TablaDatos.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        TablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idCargo", "Cargo"
            }
        ));
        jScrollPane2.setViewportView(TablaDatos);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 134, 607, 121);

        AdicionarCargo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        AdicionarCargo.setText("Adicionar");
        AdicionarCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarCargoActionPerformed(evt);
            }
        });
        getContentPane().add(AdicionarCargo);
        AdicionarCargo.setBounds(10, 74, 115, 33);

        BotonActualizar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BotonActualizar.setText("Actualizar");
        BotonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonActualizar);
        BotonActualizar.setBounds(170, 70, 119, 33);

        botonEliminar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(botonEliminar);
        botonEliminar.setBounds(512, 74, 105, 33);

        jButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton2.setText("Inicio");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 273, 79, 33);

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        jLabel1.setText("VENTANA PRINCIPAL CARGO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 10, 324, 25);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondohd.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1010, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarActionPerformed

        ArrayList<String[]> datos = conexion.consulta("SELECT idCargo,Nombre_Cargo FROM Cargo order by idCargo");
        //Salida.setText(datos);
        DefaultTableModel modelo = (DefaultTableModel)TablaDatos.getModel();
        //String cadena ="";
        while(modelo.getRowCount() > 0)
        modelo.removeRow(modelo.getRowCount()-1);

        for (int i = 0; i<datos.size(); i++){
            String[] fila = datos.get(i);
            modelo.addRow(fila);
            /*for(int j = 0; j<fila.length; j++){
                cadena += fila[j]+ ",";
            }
            cadena += "\n";
        }
        //Salida.setText(cadena);
        */
        }
    }//GEN-LAST:event_botonConsultarActionPerformed

    private void AdicionarCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarCargoActionPerformed

          this.setVisible(false);
        new NuevaCargo(this,true).setVisible(true);

    }//GEN-LAST:event_AdicionarCargoActionPerformed

    private void BotonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActualizarActionPerformed
      
        
          this.setVisible(false);
        new ActualizarCargo(this,true).setVisible(true);
    }//GEN-LAST:event_BotonActualizarActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        //ConexionDB conexion = new ConexionDB();
        
        //setVisible(true);

        if (JOptionPane.showConfirmDialog(this, "¿Esta seguro de borrar este Cargo?")== 0){

            try{
                
                DefaultTableModel modelo = (DefaultTableModel)TablaDatos.getModel();
        int numFila = TablaDatos.getSelectedRow();
        String id = (String)modelo.getValueAt(numFila, 0);
        String sql = "DELETE FROM Cargo WHERE idCargo = '"+ id + "'";
        conexion.Sentencia(sql);
        
                int[] x = TablaDatos.getSelectedRows();
                for(int i=0; i<x.length; i++){
                    modelo.removeRow(TablaDatos.getSelectedRow());
                }

            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this,"Seleccione un Cargo para poder borrar");
                System.out.println(e.getMessage());

            }
        }

    }//GEN-LAST:event_botonEliminarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        new VentanaPrincipal().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalCargo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipalCargo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdicionarCargo;
    private javax.swing.JButton BotonActualizar;
    private javax.swing.JTable TablaDatos;
    private javax.swing.JButton botonConsultar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
