/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaGastos;


import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.ConexionDB;
import vistas.VentanaPrincipal;


/**
 *
 * @author EstudianteUnivalle
 */
public class ActualizarGasto extends javax.swing.JDialog {

    /**
     * Creates new form ActualizarCli
     */
    public ActualizarGasto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("../img/iconoUnivalle.JPG")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Volver = new javax.swing.JButton();
        IDGasto = new javax.swing.JTextField();
        IDBus = new javax.swing.JTextField();
        IDDescripcion = new javax.swing.JTextField();
        ValorGastos = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(380, 420));
        getContentPane().setLayout(null);

        botonGuardar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botonGuardar.setText("GUARDAR");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(botonGuardar);
        botonGuardar.setBounds(131, 288, 125, 33);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("IDGasto");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(65, 74, 69, 24);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("IDBus");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(65, 117, 52, 24);

        jLabel4.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        jLabel4.setText("ACTUALIZAR GASTO");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(65, 19, 232, 25);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Descripcion");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(65, 168, 104, 24);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setText("Valor");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(65, 221, 46, 24);

        Volver.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Volver.setText("Atras");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Volver);
        Volver.setBounds(10, 339, 79, 33);

        IDGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDGastoActionPerformed(evt);
            }
        });
        getContentPane().add(IDGasto);
        IDGasto.setBounds(206, 69, 90, 30);
        getContentPane().add(IDBus);
        IDBus.setBounds(207, 112, 90, 30);
        getContentPane().add(IDDescripcion);
        IDDescripcion.setBounds(206, 163, 90, 30);
        getContentPane().add(ValorGastos);
        ValorGastos.setBounds(206, 211, 90, 30);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("Inicio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(107, 339, 79, 33);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/emple.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 420, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
  if(
            IDGasto.getText().equals("")||
            IDBus.getText().equals("")||
            IDDescripcion.getText().equals("")||
            ValorGastos.getText().equals("")
           )
        {
          JOptionPane.showMessageDialog(this,"Llenar los valores a continuación"); 
          
        }else{
        try{
        ConexionDB conexion = new ConexionDB();
        String id = IDGasto.getText();
        String IDbus = IDBus.getText();
        String descripcion = IDDescripcion.getText();
        String Valor = ValorGastos.getText();
        
        
        String sql = "UPDATE Gastos SET idBuses = '";
        sql +=  IDbus + "', Descripcion = '" + descripcion +"', Valor = '" + Valor +"' WHERE idGastos = '" + id + "'";
        conexion.Sentencia(sql);
        setVisible(true);
        JOptionPane.showMessageDialog(this,"Datos Actualizados Exitosamente");
    } catch(Exception e){
                JOptionPane.showMessageDialog(this,"Llenar los valores a continuación");
                System.out.println(e.getMessage());
              }
  }
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed

        this.setVisible(false);
        new VentanaPrincipalGastos().setVisible(true);
    }//GEN-LAST:event_VolverActionPerformed

    private void IDGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDGastoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDGastoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new VentanaPrincipal().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ActualizarGasto dialog = new ActualizarGasto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDBus;
    private javax.swing.JTextField IDDescripcion;
    private javax.swing.JTextField IDGasto;
    private javax.swing.JTextField ValorGastos;
    private javax.swing.JButton Volver;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
