/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaGastos;


import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.ConexionDB;
import vistas.VentanaPrincipal;

/**
 *
 * @author EstudianteUnivalle
 */
public class NuevoGasto extends javax.swing.JDialog {

    /**
     * Creates new form NuevoCliente
     */
    public NuevoGasto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("../img/iconoUnivalle.JPG")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        InIDGasto = new javax.swing.JTextField();
        InIDBus = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        BotonGuardar = new javax.swing.JButton();
        InDescripcionGasto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        InValorGasto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Volver = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 430));
        setMinimumSize(new java.awt.Dimension(400, 430));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("IDGasto :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(63, 89, 81, 24);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("IDBus:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(63, 138, 59, 24);

        InIDGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InIDGastoActionPerformed(evt);
            }
        });
        getContentPane().add(InIDGasto);
        InIDGasto.setBounds(205, 79, 108, 30);

        InIDBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InIDBusActionPerformed(evt);
            }
        });
        getContentPane().add(InIDBus);
        InIDBus.setBounds(205, 133, 108, 30);

        jLabel4.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        jLabel4.setText("Ingresar Los Datos Del Gasto");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(48, 19, 287, 25);

        BotonGuardar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BotonGuardar.setText("Guardar");
        BotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonGuardar);
        BotonGuardar.setBounds(183, 279, 103, 33);
        getContentPane().add(InDescripcionGasto);
        InDescripcionGasto.setBounds(205, 180, 108, 30);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Descripcion");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(63, 190, 104, 24);

        InValorGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InValorGastoActionPerformed(evt);
            }
        });
        getContentPane().add(InValorGasto);
        InValorGasto.setBounds(205, 230, 108, 30);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("Valor");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(63, 233, 46, 28);

        Volver.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Volver.setText("Atras");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Volver);
        Volver.setBounds(10, 341, 79, 33);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("Inicio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(107, 341, 79, 33);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/emple.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 400, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarActionPerformed
   if(
            InIDGasto.getText().equals("")||
            InIDBus.getText().equals("")||
            InDescripcionGasto.getText().equals("")||
            InValorGasto.getText().equals("")
           )
        {
          JOptionPane.showMessageDialog(this,"Llenar los valores a continuación"); 
          
        }else{
        try{
        ConexionDB conexion = new ConexionDB();
        String id = InIDGasto.getText();
        String idbus = InIDBus.getText();
        String descrip = InDescripcionGasto.getText();
        String valor = InValorGasto.getText();
       
        String sql = "INSERT INTO Gastos (idGastos,idBuses,Descripcion,Valor)";
        sql += "VALUES ( '"+ id +"','"+ idbus +"','"+ descrip +"', '"+ valor +"')";
        conexion.Sentencia(sql);
       setVisible(true);
        JOptionPane.showMessageDialog(this,"Datos Ingresados Exitosamente");
     } catch(Exception e){
                JOptionPane.showMessageDialog(this,"Llenar los valores a continuación");
                System.out.println(e.getMessage());
              }
   }
    }//GEN-LAST:event_BotonGuardarActionPerformed

    private void InIDBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InIDBusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InIDBusActionPerformed

    private void InIDGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InIDGastoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InIDGastoActionPerformed

    private void InValorGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InValorGastoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InValorGastoActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed

        this.setVisible(false);
        new VentanaPrincipalGastos().setVisible(true);
    }//GEN-LAST:event_VolverActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        this.setVisible(false);
        new VentanaPrincipal().setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NuevoGasto dialog = new NuevoGasto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonGuardar;
    private javax.swing.JTextField InDescripcionGasto;
    private javax.swing.JTextField InIDBus;
    private javax.swing.JTextField InIDGasto;
    private javax.swing.JTextField InValorGasto;
    private javax.swing.JButton Volver;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
