/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaGastos;



import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.ConexionDB;
import vistas.VentanaPrincipal;


    
/**
 *
 * @author EstudianteUnivalle
 */
public class VentanaPrincipalGastos extends javax.swing.JFrame {

    DefaultTableModel modelo;
    ConexionDB conexion;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipalGastos() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("../img/iconoUnivalle.JPG")).getImage());
        modelo = (DefaultTableModel)TablaDatos.getModel();
        conexion = new ConexionDB();
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonConsultar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaDatos = new javax.swing.JTable();
        AdicionarGasto = new javax.swing.JButton();
        BotonActualizar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        GastosTotales = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(830, 400));
        setMinimumSize(new java.awt.Dimension(830, 400));
        getContentPane().setLayout(null);

        botonConsultar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botonConsultar.setText("Consultar");
        botonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(botonConsultar);
        botonConsultar.setBounds(196, 90, 117, 33);

        TablaDatos.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        TablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDGasto", "IDBus", "Descripción del Gasto", "Valor del Gasto"
            }
        ));
        jScrollPane2.setViewportView(TablaDatos);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(18, 149, 760, 121);

        AdicionarGasto.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        AdicionarGasto.setText("Adicionar");
        AdicionarGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarGastoActionPerformed(evt);
            }
        });
        getContentPane().add(AdicionarGasto);
        AdicionarGasto.setBounds(31, 90, 115, 33);

        BotonActualizar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BotonActualizar.setText("Actualizar");
        BotonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonActualizar);
        BotonActualizar.setBounds(345, 90, 119, 33);

        botonEliminar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(botonEliminar);
        botonEliminar.setBounds(498, 90, 105, 33);

        GastosTotales.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        GastosTotales.setText("GastosTotales");
        GastosTotales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GastosTotalesActionPerformed(evt);
            }
        });
        getContentPane().add(GastosTotales);
        GastosTotales.setBounds(621, 90, 157, 33);

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        jLabel1.setText("VENTANA PRINCIPAL DE GASTOS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(221, 27, 369, 25);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("Inicio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(18, 301, 79, 33);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/facturacion.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-40, 0, 910, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarActionPerformed
        
        ArrayList<String[]> datos = conexion.consulta("SELECT idGastos,idBuses,Descripcion, Valor FROM Gastos order by idGastos");
        //Salida.setText(datos);
        DefaultTableModel modelo = (DefaultTableModel)TablaDatos.getModel();
        //String cadena ="";
        while(modelo.getRowCount() > 0)
            modelo.removeRow(modelo.getRowCount()-1);
        
        for (int i = 0; i<datos.size(); i++){
            String[] fila = datos.get(i);
            modelo.addRow(fila);
            /*for(int j = 0; j<fila.length; j++){
                cadena += fila[j]+ ",";
            }
            cadena += "\n";
        }
        //Salida.setText(cadena);
     */
        }
    }//GEN-LAST:event_botonConsultarActionPerformed

    private void AdicionarGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarGastoActionPerformed
       
      
        this.setVisible(false); 
        new NuevoGasto(this,true).setVisible(true); 
        
    }//GEN-LAST:event_AdicionarGastoActionPerformed

    private void BotonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActualizarActionPerformed
    
        this.setVisible(false); 
        new ActualizarGasto(this,true).setVisible(true); 
        
    }//GEN-LAST:event_BotonActualizarActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        //ConexionDB conexion = new ConexionDB();
        
        //setVisible(true);
        
        if (JOptionPane.showConfirmDialog(this, "¿Esta seguro de borrar este Gasto?")== 0){
            
          
            
            try{ 
                
                  DefaultTableModel modelo = (DefaultTableModel)TablaDatos.getModel();
            int numFila = TablaDatos.getSelectedRow();
            String id = (String)modelo.getValueAt(numFila, 0);
            String sql = "DELETE FROM Gastos WHERE idGastos = '"+ id + "'";
            conexion.Sentencia(sql);
                
                int[] x = TablaDatos.getSelectedRows();
                for(int i=0; i<x.length; i++){
                    modelo.removeRow(TablaDatos.getSelectedRow());
                }
            
        }
        catch(Exception e){
                JOptionPane.showMessageDialog(this,"Seleccione un Gasto para poder borrar");
                System.out.println(e.getMessage());
            
        }
    }
            
       
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void GastosTotalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GastosTotalesActionPerformed
  
        this.setVisible(false); 
        new GastosTotales().setVisible(true); 
        
    }//GEN-LAST:event_GastosTotalesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new VentanaPrincipal().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipalGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipalGastos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdicionarGasto;
    private javax.swing.JButton BotonActualizar;
    private javax.swing.JButton GastosTotales;
    private javax.swing.JTable TablaDatos;
    private javax.swing.JButton botonConsultar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
