
package VistaBuses;

import vistas.VentanaPrincipal;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.ConexionDB;

/**
 *
 * @author EstudianteUnivalle
 */
public class NuevoBus extends javax.swing.JDialog {

    /**
     * Creates new form NuevoCliente
     */
    public NuevoBus(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("../img/iconoUnivalle.JPG")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PLACA = new javax.swing.JLabel();
        InPlacaBus = new javax.swing.JTextField();
        InCapacidadBus = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        InIDBus = new javax.swing.JTextField();
        BotonGuardar = new javax.swing.JButton();
        InIDBus1 = new javax.swing.JTextField();
        InPlacaBus1 = new javax.swing.JTextField();
        InCapacidadBus1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PLACA1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        PLACA.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        PLACA.setText("PLACA");

        InPlacaBus.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        InPlacaBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InPlacaBusActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel13.setText("Ingresar Los Datos Del Cliente");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setText("IDBUS :");

        jLabel11.setText("Capacidad");

        InIDBus.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        InIDBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InIDBusActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 440));
        setMinimumSize(new java.awt.Dimension(500, 440));
        getContentPane().setLayout(null);

        BotonGuardar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        BotonGuardar.setText("Guardar");
        BotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonGuardar);
        BotonGuardar.setBounds(157, 269, 103, 33);

        InIDBus1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        InIDBus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InIDBus1ActionPerformed(evt);
            }
        });
        getContentPane().add(InIDBus1);
        InIDBus1.setBounds(219, 84, 108, 30);

        InPlacaBus1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        InPlacaBus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InPlacaBus1ActionPerformed(evt);
            }
        });
        getContentPane().add(InPlacaBus1);
        InPlacaBus1.setBounds(219, 143, 108, 30);
        getContentPane().add(InCapacidadBus1);
        InCapacidadBus1.setBounds(219, 196, 108, 30);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Capacidad");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 206, 91, 24);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("IDBUS :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 92, 68, 24);

        jLabel4.setFont(new java.awt.Font("Kristen ITC", 1, 24)); // NOI18N
        jLabel4.setText("Ingresar Los Datos Del Bus");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(56, 21, 349, 33);

        PLACA1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        PLACA1.setText("PLACA");
        getContentPane().add(PLACA1);
        PLACA1.setBounds(90, 151, 62, 24);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 340, 79, 33);

        jButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton2.setText("Inicio");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(140, 340, 90, 33);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/emple.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 630, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InIDBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InIDBusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InIDBusActionPerformed

    private void InPlacaBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InPlacaBusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InPlacaBusActionPerformed

    private void BotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarActionPerformed
 if(
            InIDBus1.getText().equals("")||
            InPlacaBus1.getText().equals("")||
            InCapacidadBus1.getText().equals("")
           )
        {
          JOptionPane.showMessageDialog(this,"Llenar los valores a continuación"); 
          
        }else{
        try{
        ConexionDB conexion = new ConexionDB();
        String id = InIDBus1.getText();
        String placa = InPlacaBus1.getText();
        String capacidad = InCapacidadBus1.getText();
        

        String sql = "INSERT INTO Buses (idBuses,Placa,Capacidad_Pasajeros)";
        sql += "VALUES ('"+id+"','"+placa+"','"+capacidad+"')";
        conexion.Sentencia(sql);
        setVisible(false);
        JOptionPane.showMessageDialog(this,"Datos Ingresados Exitosamente");
} catch(Exception e){
                JOptionPane.showMessageDialog(this,"Llenar los valores a continuación");
                System.out.println(e.getMessage());
              }
 }
    }//GEN-LAST:event_BotonGuardarActionPerformed

    private void InIDBus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InIDBus1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InIDBus1ActionPerformed

    private void InPlacaBus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InPlacaBus1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InPlacaBus1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new VentanaPrincipalBuses().setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        new VentanaPrincipal().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NuevoBus dialog = new NuevoBus(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonGuardar;
    private javax.swing.JTextField InCapacidadBus;
    private javax.swing.JTextField InCapacidadBus1;
    private javax.swing.JTextField InIDBus;
    private javax.swing.JTextField InIDBus1;
    private javax.swing.JTextField InPlacaBus;
    private javax.swing.JTextField InPlacaBus1;
    private javax.swing.JLabel PLACA;
    private javax.swing.JLabel PLACA1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
